# Development Configuration
database:
  url: postgresql://postgres:postgres@db:5432/clerkk

auth0:
  domain: technotut.au.auth0.com
  api_audience: https://api.inbriefs.com

aws:
  region: ca-central-1

cors:
  allowed_origins:
    - "*"

app:
  environment: development
  log_level: DEBUG
  debug: true
