# Production Configuration
database:
  url: /clerkk/db/connection_string

auth0:
  domain: technotut.au.auth0.com
  api_audience: https://api.inbriefs.com

aws:
  region: ca-central-1

cors:
  allowed_origins:
    - "*"

app:
  environment: production
  log_level: INFO
  debug: false
