/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/income/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Income
     * @description Create user income profile (onboarding)
     */
    post: operations['create_income_income__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/income/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log Income Event
     * @description Log income event (paycheck, bonus, etc.)
     */
    post: operations['log_income_event_income_events_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Expense
     * @description Create expense(s) - accepts single object or array
     */
    post: operations['create_expense_expenses__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses/{expense_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Expense
     * @description Update expense amount
     */
    put: operations['update_expense_expenses__expense_id__put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/expenses/total': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Total Expenses
     * @description Get total monthly expenses
     */
    get: operations['get_total_expenses_expenses_total_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Current User Profile
     * @description Get current user profile
     */
    get: operations['get_current_user_profile_user_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/complete-onboarding': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete Onboarding
     * @description Mark onboarding as complete
     */
    post: operations['complete_onboarding_user_complete_onboarding_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Dashboard Stats
     * @description Get dashboard statistics for monthly or yearly view
     */
    get: operations['get_dashboard_stats_dashboard_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/debts/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Debts
     * @description Get all active debts for user
     */
    get: operations['get_debts_debts__get'];
    put?: never;
    /**
     * Create Debt
     * @description Create a new debt
     */
    post: operations['create_debt_debts__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/debts/{debt_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update Debt
     * @description Update a debt
     */
    put: operations['update_debt_debts__debt_id__put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/debts/total': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Total Debt
     * @description Get total monthly debt payments in CAD
     */
    get: operations['get_total_debt_debts_total_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/accounts/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Accounts */
    get: operations['get_accounts_accounts__get'];
    put?: never;
    /** Create Account */
    post: operations['create_account_accounts__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/accounts/{account_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Account */
    get: operations['get_account_accounts__account_id__get'];
    /** Update Account */
    put: operations['update_account_accounts__account_id__put'];
    post?: never;
    /** Delete Account */
    delete: operations['delete_account_accounts__account_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/accounts/{account_id}/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add Ledger Event */
    post: operations['add_ledger_event_accounts__account_id__events_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/accounts/{account_id}/history': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Account History */
    get: operations['get_account_history_accounts__account_id__history_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations['root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Check */
    get: operations['health_check_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountCreate */
    AccountCreate: {
      /** Name */
      name: string;
      account_type: components['schemas']['AccountType'];
      /** Initial Balance */
      initial_balance: number | string;
      /** Purpose */
      purpose?: string | null;
      /** Goal Amount */
      goal_amount?: number | string | null;
      /** Goal Date */
      goal_date?: string | null;
      /** Annual Contribution Limit */
      annual_contribution_limit?: number | string | null;
      /** Limit Year */
      limit_year?: number | null;
    };
    /** AccountResponse */
    AccountResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      account_type: components['schemas']['AccountType'];
      /** Current Balance */
      current_balance: string;
      /** Purpose */
      purpose: string | null;
      /** Goal Amount */
      goal_amount: string | null;
      /** Goal Date */
      goal_date: string | null;
      /** Annual Contribution Limit */
      annual_contribution_limit: string | null;
      /** Limit Year */
      limit_year: number | null;
      /** Contributions This Year */
      contributions_this_year?: string | null;
      /** Remaining Contribution Room */
      remaining_contribution_room?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * AccountType
     * @enum {string}
     */
    AccountType: 'cash' | 'investment' | 'rrsp' | 'tfsa';
    /** AccountUpdate */
    AccountUpdate: {
      /** Name */
      name?: string | null;
      /** Purpose */
      purpose?: string | null;
      /** Goal Amount */
      goal_amount?: number | string | null;
      /** Goal Date */
      goal_date?: string | null;
      /** Annual Contribution Limit */
      annual_contribution_limit?: number | string | null;
      /** Limit Year */
      limit_year?: number | null;
    };
    /** AccountWithHistory */
    AccountWithHistory: {
      account: components['schemas']['AccountResponse'];
      /** History */
      history: components['schemas']['LedgerEventResponse'][];
      /** Remaining Contribution Room */
      remaining_contribution_room?: string | null;
    };
    /** DashboardResponse */
    DashboardResponse: {
      /**
       * Period
       * @enum {string}
       */
      period: 'monthly' | 'yearly';
      stats: components['schemas']['DashboardStats'];
    };
    /** DashboardStats */
    DashboardStats: {
      /** Surplus */
      surplus: string;
      /** Income */
      income: string;
      /** Post Tax Income */
      post_tax_income: string;
      /** Taxes */
      taxes: string;
      /** Expenses */
      expenses: string;
      /** Debt */
      debt: string;
      /** Effective Tax Rate */
      effective_tax_rate: string;
      /** Marginal Tax Rate */
      marginal_tax_rate: string;
      /** Income Percentile */
      income_percentile: string;
    };
    /** DebtCreate */
    DebtCreate: {
      /**
       * Name
       * @description Debt name (e.g., 'TD Mortgage')
       */
      name: string;
      type: components['schemas']['DebtType'];
      /** Monthly Payment */
      monthly_payment: number | string;
      /** Current Balance */
      current_balance: number | string;
      /**
       * Interest Rate
       * @description Annual rate (e.g., 3.5)
       */
      interest_rate: number | string;
      /**
       * Currency
       * @default CAD
       */
      currency: string;
      /** Original Principal */
      original_principal?: number | string | null;
      /** Term Months */
      term_months?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** DebtResponse */
    DebtResponse: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Type */
      type: string;
      /** Currency */
      currency: string;
      /** Monthly Payment */
      monthly_payment: string;
      /** Current Balance */
      current_balance: string;
      /** Interest Rate */
      interest_rate: string;
      /** Original Principal */
      original_principal?: string | null;
      /** Term Months */
      term_months?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** Is Active */
      is_active: boolean;
      /** Notes */
      notes?: string | null;
    };
    /**
     * DebtType
     * @enum {string}
     */
    DebtType: 'mortgage' | 'loan' | 'credit_card' | 'line_of_credit';
    /** DebtUpdate */
    DebtUpdate: {
      /** Name */
      name?: string | null;
      /** Monthly Payment */
      monthly_payment?: number | string | null;
      /** Current Balance */
      current_balance?: number | string | null;
      /** Interest Rate */
      interest_rate?: number | string | null;
      /** Original Principal */
      original_principal?: number | string | null;
      /** Term Months */
      term_months?: number | null;
      /** Start Date */
      start_date?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Notes */
      notes?: string | null;
    };
    /**
     * EventType
     * @enum {string}
     */
    EventType: 'contribute' | 'withdraw' | 'update_balance';
    /** ExpenseCreate */
    ExpenseCreate: {
      /** Category */
      category: string;
      /** Name */
      name: string;
      /** Amount */
      amount: number | string;
    };
    /** ExpenseResponse */
    ExpenseResponse: {
      /** Id */
      id: number;
      /** User Id */
      user_id: string;
      /** Category */
      category: string;
      /** Name */
      name: string;
      /** Amount */
      amount: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Updated At */
      updated_at?: string | null;
    };
    /** ExpenseUpdate */
    ExpenseUpdate: {
      /** Amount */
      amount: number | string;
      /** Reason */
      reason?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IncomeEventCreate */
    IncomeEventCreate: {
      /** Source Id */
      source_id?: number | null;
      /** Event Type */
      event_type: string;
      /** Gross Amount */
      gross_amount?: number | string | null;
      /** Net Amount */
      net_amount: number | string;
      /** Region */
      region: string;
      /**
       * Event Date
       * Format: date
       */
      event_date: string;
      /** Notes */
      notes?: string | null;
    };
    /** LedgerEventCreate */
    LedgerEventCreate: {
      event_type: components['schemas']['EventType'];
      /** Amount */
      amount?: number | string | null;
      /** Balance Snapshot */
      balance_snapshot?: number | string | null;
      /** Source */
      source?: string | null;
      /** Event Date */
      event_date?: string | null;
      /** Notes */
      notes?: string | null;
    };
    /** LedgerEventResponse */
    LedgerEventResponse: {
      /** Id */
      id: string;
      event_type: components['schemas']['EventType'];
      /** Amount */
      amount: string | null;
      /** Balance Snapshot */
      balance_snapshot: string;
      /** Source */
      source: string | null;
      /**
       * Event Date
       * Format: date-time
       */
      event_date: string;
      /** Notes */
      notes: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** OnboardingCompleteResponse */
    OnboardingCompleteResponse: {
      /** Message */
      message: string;
      /** User Id */
      user_id: string;
    };
    /** UserIncomeCreate */
    UserIncomeCreate: {
      /** Gross Annual Estimate */
      gross_annual_estimate: number | string;
    };
    /** UserProfileResponse */
    UserProfileResponse: {
      /** User Id */
      user_id: string;
      /** Email */
      email?: string | null;
      /** Country */
      country: string;
      /** Region */
      region: string;
      /** Onboarding Completed */
      onboarding_completed: boolean;
      /** Created At */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  create_income_income__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserIncomeCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  log_income_event_income_events_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IncomeEventCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_expense_expenses__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json':
          | components['schemas']['ExpenseCreate']
          | components['schemas']['ExpenseCreate'][];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json':
            | components['schemas']['ExpenseResponse']
            | components['schemas']['ExpenseResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_expense_expenses__expense_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        expense_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ExpenseUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_total_expenses_expenses_total_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  get_current_user_profile_user_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserProfileResponse'];
        };
      };
    };
  };
  complete_onboarding_user_complete_onboarding_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OnboardingCompleteResponse'];
        };
      };
    };
  };
  get_dashboard_stats_dashboard_stats_get: {
    parameters: {
      query?: {
        period?: 'monthly' | 'yearly';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_debts_debts__get: {
    parameters: {
      query?: {
        /** @description Convert all amounts to this currency */
        display_currency?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DebtResponse'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_debt_debts__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DebtCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DebtResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_debt_debts__debt_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        debt_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DebtUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DebtResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_total_debt_debts_total_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_accounts_accounts__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'][];
        };
      };
    };
  };
  create_account_accounts__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_account_accounts__account_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_account_accounts__account_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_account_accounts__account_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_ledger_event_accounts__account_id__events_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LedgerEventCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LedgerEventResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_account_history_accounts__account_id__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccountWithHistory'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  health_check_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
