"""Add accounts and keep debts

Revision ID: 0dcf7a2e3895
Revises:
Create Date: 2026-03-05 23:21:30.058216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0dcf7a2e3895"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("CASH", "INVESTMENT", "RRSP", "TFSA", name="accounttype"),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("goal_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("goal_date", sa.Date(), nullable=True),
        sa.Column(
            "annual_contribution_limit",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column("limit_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_accounts_user_id"), "user_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "account_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("CONTRIBUTE", "WITHDRAW", "UPDATE_BALANCE", name="eventtype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "balance_snapshot", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["user_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_ledger_account_id"),
        "account_ledger",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_ledger_event_date"),
        "account_ledger",
        ["event_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_ledger_event_date"), table_name="account_ledger")
    op.drop_index(op.f("ix_account_ledger_account_id"), table_name="account_ledger")
    op.drop_table("account_ledger")
    op.drop_index(op.f("ix_user_accounts_user_id"), table_name="user_accounts")
    op.drop_table("user_accounts")
    # ### end Alembic commands ###
