"""initial schema

Revision ID: ec9c4e39ee48
Revises:
Create Date: 2026-03-08 01:05:35.919889

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ec9c4e39ee48"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("auth0_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("region", sa.String(length=2), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth0_id"), "users", ["auth0_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "expenses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expenses_user_id"), "expenses", ["user_id"], unique=False)
    op.create_table(
        "income_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column(
            "gross_annual_estimate", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("monthly_net", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("pay_frequency", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_income_sources_user_id"), "income_sources", ["user_id"], unique=False
    )
    op.create_table(
        "user_accounts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "account_type",
            sa.Enum("CASH", "INVESTMENT", "RRSP", "TFSA", name="accounttype"),
            nullable=False,
        ),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("goal_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("goal_date", sa.Date(), nullable=True),
        sa.Column(
            "annual_contribution_limit",
            sa.Numeric(precision=12, scale=2),
            nullable=True,
        ),
        sa.Column("limit_year", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_accounts_user_id"), "user_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "user_debts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("monthly_payment", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("interest_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "original_principal", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("payment_frequency", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_income",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "gross_annual_estimate", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column(
            "total_monthly_net", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "account_ledger",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum("CONTRIBUTE", "WITHDRAW", "UPDATE_BALANCE", name="eventtype"),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "balance_snapshot", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"], ["user_accounts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_ledger_account_id"),
        "account_ledger",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_ledger_event_date"),
        "account_ledger",
        ["event_date"],
        unique=False,
    )
    op.create_table(
        "expense_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("old_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("new_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["expense_id"], ["expenses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expense_history_expense_id"),
        "expense_history",
        ["expense_id"],
        unique=False,
    )
    op.create_table(
        "income_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("gross_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("region", sa.String(length=2), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "logged_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["income_sources.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_income_events_event_date"),
        "income_events",
        ["event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_income_events_logged_at"), "income_events", ["logged_at"], unique=False
    )
    op.create_index(
        op.f("ix_income_events_user_id"), "income_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_income_events_user_id"), table_name="income_events")
    op.drop_index(op.f("ix_income_events_logged_at"), table_name="income_events")
    op.drop_index(op.f("ix_income_events_event_date"), table_name="income_events")
    op.drop_table("income_events")
    op.drop_index(op.f("ix_expense_history_expense_id"), table_name="expense_history")
    op.drop_table("expense_history")
    op.drop_index(op.f("ix_account_ledger_event_date"), table_name="account_ledger")
    op.drop_index(op.f("ix_account_ledger_account_id"), table_name="account_ledger")
    op.drop_table("account_ledger")
    op.drop_table("user_income")
    op.drop_table("user_debts")
    op.drop_index(op.f("ix_user_accounts_user_id"), table_name="user_accounts")
    op.drop_table("user_accounts")
    op.drop_index(op.f("ix_income_sources_user_id"), table_name="income_sources")
    op.drop_table("income_sources")
    op.drop_index(op.f("ix_expenses_user_id"), table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth0_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
